project:
  type: website

website:
  title: "Intro to Shiny for Python / Conf(2024)"
  navbar:
    logo: https://d33wubrfki0l68.cloudfront.net/71003073848110093780ea9a1c721439ad6b64f3/655ba/shiny-for-python.svg
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: Pre-requisites
        file: docs/pre-requisites.qmd

      - text: "Course material"
        file: docs/course.qmd

    tools: 
      - icon: github
        href: https://github.com/andrie/conf-2024-intro-to-shiny-for-python
      - icon: discord
        href: https://discord.gg/AQVJzG2bnN

  sidebar:
      # - href: index.qmd
      #   text: Home
      # - docs/pre-requisites.qmd 
      # - href: docs/housekeeping.qmd
      #   text: Housekeeping
    - title: "Course material"
      contents:
        - docs/course.qmd
        - section: "Getting Started"
          contents:
            - href: slides/getting-started.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - exercises/1-hello-world.qmd
              - exercises/2-debug.qmd
              - exercises/3-add-filter.qmd
              - exercises/4-add-plot.qmd
        - section: "Reactivity"
          contents:
            - href: slides/reactivity.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - exercises/5-reactivity.qmd
              - exercises/6-reactive-event.qmd
              - exercises/7-reactive-effects.qmd

    # - title: "Bonus Material"
    #   contents:
    #   - docs/bonus.qmd
        - section: "UI Customization"
          contents:
            - href: slides/ui-customization.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - exercises/8-navsets.qmd
              - exercises/9-cards.qmd
              - exercises/10-layout.qmd
              - exercises/11-value-boxes.qmd
              - exercises/12-dynamic-ui.qmd
        - section: "Best practices"
          contents:
            - href: slides/workflow-best-practices.qmd
              text: Slides
            - section: "Exercises"
              contents: 
              - exercises/13-ui-functions.qmd
              - exercises/14-extract-functions.qmd

      # - title: References
      #   contents:
      #     - docs/references.qmd


filters:
  - shinylive

format:
  html:
    theme: materia
    css: styles.css
    toc: true



