
on:
  workflow_dispatch:

name: Trial

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4